# Generated by Django 3.0.6 on 2020-05-22 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialinventory',
            options={'verbose_name': '物资库存', 'verbose_name_plural': '物资库存'},
        ),
    ]
