# Generated by Django 3.0.6 on 2020-05-22 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Materials', '0002_auto_20200522_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materialinventory',
            old_name='DLWZLC',
            new_name='DLWZMC',
        ),
        migrations.RenameField(
            model_name='materialinventory',
            old_name='DMLWZMC',
            new_name='DMLWZBH',
        ),
    ]
