# Generated by Django 3.0.6 on 2020-05-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Materials', '0005_auto_20200526_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialplan',
            name='specification',
            field=models.CharField(max_length=10, verbose_name='物资规格'),
        ),
    ]
