# Generated by Django 3.0.6 on 2020-05-27 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20200522_1738'),
        ('Materials', '0007_stockmaterials'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasedMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.CharField(max_length=10, verbose_name='订单编号')),
                ('number', models.CharField(max_length=15, verbose_name='物资编号')),
                ('name', models.CharField(max_length=10, verbose_name='物资名称')),
                ('specification', models.CharField(max_length=10, verbose_name='物资规格')),
                ('count', models.IntegerField(verbose_name='数量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='单价')),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='总价')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='User.Buyer', verbose_name='采购员')),
            ],
            options={
                'verbose_name': '已采购物资',
                'verbose_name_plural': '已采购物资',
            },
        ),
    ]
