# Generated by Django 3.0.6 on 2020-05-27 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20200522_1738'),
        ('Materials', '0008_purchasedmaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageMaterials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_num', models.CharField(max_length=10, verbose_name='入库编号')),
                ('number', models.CharField(max_length=15, verbose_name='物资编号')),
                ('name', models.CharField(max_length=10, verbose_name='物资名称')),
                ('storage_time', models.DateField(auto_now_add=True, verbose_name='入库时间')),
                ('count', models.IntegerField(verbose_name='入库物资量')),
                ('warehouseManager', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='User.WarehouseManager', verbose_name='经办人')),
            ],
            options={
                'verbose_name': '入库物资',
                'verbose_name_plural': '入库物资',
            },
        ),
    ]
