# Generated by Django 3.0.6 on 2020-05-28 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20200522_1738'),
        ('Materials', '0011_returnedmaterials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnedmaterials',
            name='count',
            field=models.IntegerField(verbose_name='退库物资量'),
        ),
        migrations.AlterField(
            model_name='returnedmaterials',
            name='returned_num',
            field=models.CharField(max_length=10, verbose_name='退库单编号'),
        ),
        migrations.AlterField(
            model_name='returnedmaterials',
            name='returned_time',
            field=models.DateField(auto_now_add=True, verbose_name='退库时间'),
        ),
        migrations.CreateModel(
            name='DeliveryMaterials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_num', models.CharField(max_length=10, verbose_name='发货单编号')),
                ('number', models.CharField(max_length=15, verbose_name='物资编号')),
                ('name', models.CharField(max_length=10, verbose_name='物资名称')),
                ('count', models.IntegerField(verbose_name='物资数量')),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='总价')),
                ('delivery_time', models.DateField(auto_now_add=True, verbose_name='发货时间')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='User.Supplier', verbose_name='供应商名称')),
            ],
            options={
                'verbose_name': '发货物资',
                'verbose_name_plural': '发货物资',
            },
        ),
    ]
