# Generated by Django 3.0.6 on 2020-05-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='编号')),
                ('name', models.CharField(max_length=12, verbose_name='姓名')),
                ('phone', models.CharField(max_length=11, verbose_name='联系电话')),
                ('password', models.CharField(max_length=10, verbose_name='密码')),
            ],
            options={
                'verbose_name': '采购员信息',
                'verbose_name_plural': '采购员信息',
            },
        ),
        migrations.CreateModel(
            name='Planner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='编号')),
                ('name', models.CharField(max_length=12, verbose_name='姓名')),
                ('phone', models.CharField(max_length=11, verbose_name='联系电话')),
                ('password', models.CharField(max_length=10, verbose_name='密码')),
            ],
            options={
                'verbose_name': '计划员信息',
                'verbose_name_plural': '计划员信息',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='编号')),
                ('name', models.CharField(max_length=12, verbose_name='名称')),
                ('address', models.CharField(max_length=12, verbose_name='地址')),
                ('phone', models.CharField(max_length=11, verbose_name='联系电话')),
                ('password', models.CharField(max_length=10, verbose_name='密码')),
            ],
            options={
                'verbose_name': '供应商信息',
                'verbose_name_plural': '供应商信息',
            },
        ),
        migrations.CreateModel(
            name='WarehouseManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='编号')),
                ('name', models.CharField(max_length=12, verbose_name='姓名')),
                ('phone', models.CharField(max_length=11, verbose_name='联系电话')),
                ('password', models.CharField(max_length=10, verbose_name='密码')),
            ],
            options={
                'verbose_name': '仓储管理员信息',
                'verbose_name_plural': '仓储管理员信息',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='position',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
