# Generated by Django 3.0.6 on 2020-05-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20200522_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='score',
            field=models.CharField(choices=[('优', '优'), ('中', '中'), ('良', '良'), ('差', '差')], default=1, max_length=1, verbose_name='评分'),
            preserve_default=False,
        ),
    ]
