# Generated by Django 3.0.6 on 2020-05-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_supplier_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='score',
            field=models.CharField(max_length=1, verbose_name='评分'),
        ),
    ]
